import type { LucideIcon } from "lucide-react-native";
import {
  Egg,
  EggFried,
  Coffee,
  Sandwich,
  UtensilsCrossed,
  IceCreamCone,
  CakeSlice,
  Cake,
  Wine,
  Martini,
  Soup,
  Salad,
  Fish,
  Drumstick,
  Wheat,
  Vegan,
  Heart,
  Cookie,
  Utensils,
  Pizza,
  Star,
  Gift,
  Timer,
  Flame,
  Cherry,
  Apple,
  Banana,
  Carrot,
  Beef,
  Milk,
  Croissant,
  Popcorn,
  Bean,
  Citrus,
  Grape,
  Ham,
  Hamburger,
  Lollipop,
  Nut,
  Popsicle,
  ChefHat,
  Beer,
  CupSoda,
  Donut,
  Candy,
  Sprout,
  Snowflake,
  Sun,
  Globe,
  Zap,
  PartyPopper,
  CookingPot,
  Sparkles,
  HandPlatter,
  GlassWater,
  LeafyGreen,
  FolderOpen,
} from "lucide-react-native";

const ICON_RULES: [string[], LucideIcon, string][] = [
  [["breakfast", "morning", "brunch"], Egg, "#f59e0b"],
  [["lunch"], Sandwich, "#16a34a"],
  [["dinner", "supper", "entree"], UtensilsCrossed, "#dc2626"],
  [["dessert", "sweet"], IceCreamCone, "#ec4899"],
  [["appetizer", "starter", "tapas"], HandPlatter, "#8b5cf6"],
  [["soup", "stew", "chili", "chowder"], Soup, "#ea580c"],
  [["salad"], Salad, "#22c55e"],
  [["pasta", "noodle"], Wheat, "#ca8a04"],
  [["pizza"], Pizza, "#dc2626"],
  [["burger", "hamburger"], Hamburger, "#d97706"],
  [["sandwich", "wrap"], Sandwich, "#16a34a"],
  [["curry"], CookingPot, "#f97316"],
  [["casserole"], CookingPot, "#92400e"],
  [["stir fry", "stirfry", "wok"], Flame, "#f97316"],
  [["cake", "cupcake"], CakeSlice, "#a855f7"],
  [["bread", "loaf"], Croissant, "#92400e"],
  [["cookie", "biscuit"], Cookie, "#d97706"],
  [["pie", "tart", "pastry"], Cake, "#a855f7"],
  [["donut", "doughnut"], Donut, "#ec4899"],
  [["candy", "chocolate", "fudge"], Candy, "#ec4899"],
  [["lollipop"], Lollipop, "#f472b6"],
  [["popsicle", "ice pop"], Popsicle, "#06b6d4"],
  [["chicken", "poultry", "turkey"], Drumstick, "#d97706"],
  [["beef", "steak", "meat"], Beef, "#b91c1c"],
  [["pork", "ham", "bacon"], Ham, "#f97316"],
  [["fish", "seafood", "shrimp", "salmon", "tuna", "sushi"], Fish, "#0ea5e9"],
  [["egg", "omelette", "frittata"], EggFried, "#eab308"],
  [["bean", "lentil", "legume", "chickpea"], Bean, "#92400e"],
  [["nut", "almond", "walnut", "pecan"], Nut, "#a16207"],
  [["fruit", "berry"], Cherry, "#e11d48"],
  [["apple"], Apple, "#16a34a"],
  [["banana"], Banana, "#eab308"],
  [["grape"], Grape, "#7c3aed"],
  [["citrus", "lemon", "lime", "orange"], Citrus, "#f59e0b"],
  [["carrot", "vegetable", "veggie"], Carrot, "#f97316"],
  [["coffee", "espresso", "latte"], Coffee, "#78350f"],
  [["tea", "matcha", "chai"], GlassWater, "#059669"],
  [["smoothie", "juice", "shake"], CupSoda, "#06b6d4"],
  [["cocktail", "margarita", "mojito"], Martini, "#6366f1"],
  [["wine"], Wine, "#7c3aed"],
  [["beer", "ale", "brew"], Beer, "#d97706"],
  [["drink", "beverage"], GlassWater, "#3b82f6"],
  [["milk", "dairy"], Milk, "#78350f"],
  [["popcorn", "movie night"], Popcorn, "#eab308"],
  [["vegan", "plant based", "plant-based"], Sprout, "#22c55e"],
  [["vegetarian"], Vegan, "#16a34a"],
  [["gluten free", "gluten-free"], Wheat, "#a16207"],
  [["healthy", "clean", "light", "low cal"], Heart, "#ef4444"],
  [["keto", "low carb", "low-carb"], Zap, "#f59e0b"],
  [["italian", "mediterranean"], Pizza, "#dc2626"],
  [["mexican", "tex-mex", "taco", "burrito"], Flame, "#ea580c"],
  [["asian", "chinese", "japanese", "korean", "thai", "vietnamese"], Utensils, "#e11d48"],
  [["indian"], Flame, "#f97316"],
  [["french"], Croissant, "#3b82f6"],
  [["greek"], Salad, "#0ea5e9"],
  [["bbq", "barbecue", "grill"], Flame, "#f97316"],
  [["bake", "baking"], CakeSlice, "#a855f7"],
  [["slow cook", "crockpot", "instant pot", "pressure cook"], CookingPot, "#92400e"],
  [["quick", "fast", "easy", "weeknight", "under 30"], Timer, "#3b82f6"],
  [["meal prep", "batch", "freezer"], Snowflake, "#0ea5e9"],
  [["holiday", "christmas", "thanksgiving", "easter", "halloween"], Gift, "#059669"],
  [["party", "potluck", "entertaining"], PartyPopper, "#ec4899"],
  [["summer", "spring"], Sun, "#f59e0b"],
  [["winter", "fall", "autumn", "comfort"], Snowflake, "#64748b"],
  [["favorite", "best", "top"], Star, "#eab308"],
  [["family", "kid", "children"], Heart, "#ec4899"],
  [["date night", "romantic"], Sparkles, "#ec4899"],
  [["world", "international", "global"], Globe, "#3b82f6"],
  [["chef", "special", "gourmet"], ChefHat, "#1e293b"],
  [["try", "new", "experiment"], Sparkles, "#8b5cf6"],
  [["snack"], Cookie, "#d97706"],
  [["side", "sides"], LeafyGreen, "#22c55e"],
];

export function getCollectionIcon(name: string): { Icon: LucideIcon; color: string } {
  const lower = name.toLowerCase();
  for (const [keywords, Icon, color] of ICON_RULES) {
    if (keywords.some((kw) => lower.includes(kw))) {
      return { Icon, color };
    }
  }
  return { Icon: FolderOpen, color: "#b8860b" };
}
