import type { LucideIcon } from "lucide-react-native";
import {
  Egg,
  EggFried,
  Coffee,
  Sandwich,
  UtensilsCrossed,
  IceCreamCone,
  CakeSlice,
  Cake,
  Wine,
  Martini,
  Soup,
  Salad,
  Fish,
  Drumstick,
  Wheat,
  Vegan,
  Heart,
  Cookie,
  Utensils,
  Pizza,
  Star,
  Gift,
  Timer,
  Flame,
  Cherry,
  Apple,
  Banana,
  Carrot,
  Beef,
  Milk,
  Croissant,
  Popcorn,
  Bean,
  Citrus,
  Grape,
  Ham,
  Hamburger,
  Lollipop,
  Nut,
  Popsicle,
  ChefHat,
  Beer,
  CupSoda,
  Donut,
  Candy,
  Sprout,
  Snowflake,
  Sun,
  Globe,
  Zap,
  PartyPopper,
  CookingPot,
  Sparkles,
  HandPlatter,
  GlassWater,
  LeafyGreen,
  FolderOpen,
} from "lucide-react-native";
import {
  GOLDEN_AMBER,
  SAGE_GREEN,
  PAPRIKA,
  WARM_TAUPE,
  DUSTY_TERRACOTTA,
  MUTED_PLUM,
  DUSTY_ROSE,
  DARK_WARM_GRAY,
  WARM_GRAY,
} from "../../theme/colors";

const ICON_RULES: [string[], LucideIcon, string][] = [
  [["breakfast", "morning", "brunch"], Egg, "#f59e0b"],
  [["lunch"], Sandwich, SAGE_GREEN],
  [["dinner", "supper", "entree"], UtensilsCrossed, PAPRIKA],
  [["dessert", "sweet"], IceCreamCone, DUSTY_ROSE],
  [["appetizer", "starter", "tapas"], HandPlatter, MUTED_PLUM],
  [["soup", "stew", "chili", "chowder"], Soup, "#ea580c"],
  [["salad"], Salad, SAGE_GREEN],
  [["pasta", "noodle"], Wheat, "#ca8a04"],
  [["pizza"], Pizza, PAPRIKA],
  [["burger", "hamburger"], Hamburger, "#d97706"],
  [["sandwich", "wrap"], Sandwich, SAGE_GREEN],
  [["curry"], CookingPot, "#f97316"],
  [["casserole"], CookingPot, "#92400e"],
  [["stir fry", "stirfry", "wok"], Flame, "#f97316"],
  [["cake", "cupcake"], CakeSlice, MUTED_PLUM],
  [["bread", "loaf"], Croissant, "#92400e"],
  [["cookie", "biscuit"], Cookie, "#d97706"],
  [["pie", "tart", "pastry"], Cake, MUTED_PLUM],
  [["donut", "doughnut"], Donut, DUSTY_ROSE],
  [["candy", "chocolate", "fudge"], Candy, DUSTY_ROSE],
  [["lollipop"], Lollipop, DUSTY_ROSE],
  [["popsicle", "ice pop"], Popsicle, DUSTY_TERRACOTTA],
  [["chicken", "poultry", "turkey"], Drumstick, "#d97706"],
  [["beef", "steak", "meat"], Beef, PAPRIKA],
  [["pork", "ham", "bacon"], Ham, "#f97316"],
  [["fish", "seafood", "shrimp", "salmon", "tuna", "sushi"], Fish, WARM_TAUPE],
  [["egg", "omelette", "frittata"], EggFried, GOLDEN_AMBER],
  [["bean", "lentil", "legume", "chickpea"], Bean, "#92400e"],
  [["nut", "almond", "walnut", "pecan"], Nut, "#a16207"],
  [["fruit", "berry"], Cherry, DUSTY_ROSE],
  [["apple"], Apple, SAGE_GREEN],
  [["banana"], Banana, GOLDEN_AMBER],
  [["grape"], Grape, MUTED_PLUM],
  [["citrus", "lemon", "lime", "orange"], Citrus, "#f59e0b"],
  [["carrot", "vegetable", "veggie"], Carrot, "#f97316"],
  [["coffee", "espresso", "latte"], Coffee, "#78350f"],
  [["tea", "matcha", "chai"], GlassWater, SAGE_GREEN],
  [["smoothie", "juice", "shake"], CupSoda, DUSTY_TERRACOTTA],
  [["cocktail", "margarita", "mojito"], Martini, WARM_TAUPE],
  [["wine"], Wine, MUTED_PLUM],
  [["beer", "ale", "brew"], Beer, "#d97706"],
  [["drink", "beverage"], GlassWater, GOLDEN_AMBER],
  [["milk", "dairy"], Milk, "#78350f"],
  [["popcorn", "movie night"], Popcorn, GOLDEN_AMBER],
  [["vegan", "plant based", "plant-based"], Sprout, SAGE_GREEN],
  [["vegetarian"], Vegan, SAGE_GREEN],
  [["gluten free", "gluten-free"], Wheat, "#a16207"],
  [["healthy", "clean", "light", "low cal"], Heart, PAPRIKA],
  [["keto", "low carb", "low-carb"], Zap, "#f59e0b"],
  [["italian", "mediterranean"], Pizza, PAPRIKA],
  [["mexican", "tex-mex", "taco", "burrito"], Flame, "#ea580c"],
  [["asian", "chinese", "japanese", "korean", "thai", "vietnamese"], Utensils, DUSTY_ROSE],
  [["indian"], Flame, "#f97316"],
  [["french"], Croissant, GOLDEN_AMBER],
  [["greek"], Salad, WARM_TAUPE],
  [["bbq", "barbecue", "grill"], Flame, "#f97316"],
  [["bake", "baking"], CakeSlice, MUTED_PLUM],
  [["slow cook", "crockpot", "instant pot", "pressure cook"], CookingPot, "#92400e"],
  [["quick", "fast", "easy", "weeknight", "under 30"], Timer, GOLDEN_AMBER],
  [["meal prep", "batch", "freezer"], Snowflake, WARM_TAUPE],
  [["holiday", "christmas", "thanksgiving", "easter", "halloween"], Gift, SAGE_GREEN],
  [["party", "potluck", "entertaining"], PartyPopper, DUSTY_ROSE],
  [["summer", "spring"], Sun, "#f59e0b"],
  [["winter", "fall", "autumn", "comfort"], Snowflake, WARM_GRAY],
  [["favorite", "best", "top"], Star, GOLDEN_AMBER],
  [["family", "kid", "children"], Heart, DUSTY_ROSE],
  [["date night", "romantic"], Sparkles, DUSTY_ROSE],
  [["world", "international", "global"], Globe, GOLDEN_AMBER],
  [["chef", "special", "gourmet"], ChefHat, DARK_WARM_GRAY],
  [["try", "new", "experiment"], Sparkles, MUTED_PLUM],
  [["snack"], Cookie, "#d97706"],
  [["side", "sides"], LeafyGreen, SAGE_GREEN],
];

export function getCollectionIcon(name: string): { Icon: LucideIcon; color: string } {
  const lower = name.toLowerCase();
  for (const [keywords, Icon, color] of ICON_RULES) {
    if (keywords.some((kw) => lower.includes(kw))) {
      return { Icon, color };
    }
  }
  return { Icon: FolderOpen, color: "#b8860b" };
}
